services:
  db:
    image: mysql:8.0
    container_name: catasto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init/Catasto.sql:/docker-entrypoint-initdb.d/Catasto.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 20
      interval: 10s

  backend:
    image: ipavon/catasto1427-backend:latest
    container_name: catasto-backend
    restart: always
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=3306
      - DB_SSL=false
      - PORT=3005
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ipavon/catasto1427-frontend:latest
    container_name: catasto-frontend
    restart: always
    ports:
      - "1427:80"
    depends_on:
      - backend
